org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true

loom_version = 1.13.+

mod_version = 4.0.0

# https://fabricmc.net/develop
minecraft_version = 1.21.11
minecraft_dependency = >=1.21.11 <=1.21.12
loader_version = 0.18.2
fabric_api_version = 0.139.4+1.21.11

# Mixin Extra's
# https://github.com/LlamaLad7/MixinExtras
# If set to 'none' Mixin Extra's will not be JiJ'd and Porting Lib will use whatever version fabric loader bundles
# ! Reason: Expressions
mixin_extras_version = none

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version = 1.21.10
parchment_version = 2025.10.12

# dev env mods
# https://modrinth.com/mod/lithium
lithium_version = mc1.21.11-0.21.0-fabric
# https://modrinth.com/mod/iris
iris_version = 1.10.1+1.21.11-fabric
# https://modrinth.com/mod/modmenu
modmenu_version = 17.0.0-alpha.1
# https://modrinth.com/mod/vmp-fabric
vmp_version = 0.2.0+beta.7.222+1.21.11
