package io.github.fabricators_of_create.porting_lib.util;

import io.github.fabricators_of_create.porting_lib.entity.MultiPartEntity;
import io.github.fabricators_of_create.porting_lib.entity.PartEntity;
import io.github.fabricators_of_create.porting_lib.event.common.BlockEvents;
import io.github.fabricators_of_create.porting_lib.event.common.EntityEvents;
import io.github.fabricators_of_create.porting_lib.event.common.ModsLoadedCallback;
import io.github.fabricators_of_create.porting_lib.extensions.BlockItemExtensions;
import io.github.fabricators_of_create.porting_lib.loot.IGlobalLootModifier;
import io.github.fabricators_of_create.porting_lib.loot.LootModifierManager;
import io.github.fabricators_of_create.porting_lib.util.client.ClientHooks;
import net.fabricmc.api.EnvType;
import net.fabricmc.fabric.api.client.render.fluid.v1.SimpleFluidRenderHandler;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents;
import net.fabricmc.fabric.api.event.registry.RegistryEntryRemovedCallback;
import net.fabricmc.fabric.api.transfer.v1.client.fluid.FluidVariantRendering;
import net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant;
import net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariantAttributeHandler;
import net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariantAttributes;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.block.BlockState;
import net.minecraft.block.entity.BlockEntity;
import net.minecraft.block.pattern.CachedBlockPosition;
import net.minecraft.client.texture.Sprite;
import net.minecraft.enchantment.EnchantmentHelper;
import net.minecraft.entity.Entity;
import net.minecraft.entity.ItemEntity;
import net.minecraft.entity.LivingEntity;
import net.minecraft.entity.damage.DamageSource;
import net.minecraft.fluid.FlowableFluid;
import net.minecraft.fluid.Fluid;
import net.minecraft.fluid.Fluids;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.loot.context.LootContext;
import net.minecraft.network.Packet;
import net.minecraft.network.packet.s2c.play.BlockUpdateS2CPacket;
import net.minecraft.server.ServerTask;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.registry.Registry;
import net.minecraft.util.thread.ThreadExecutor;
import net.minecraft.world.GameMode;
import net.minecraft.world.World;
import org.jetbrains.annotations.Nullable;

import java.util.List;

@SuppressWarnings({"removal", "UnstableApiUsage"})
public class PortingHooks {
	public static int onBlockBreakEvent(World world, GameMode gameType, ServerPlayerEntity entityPlayer, BlockPos pos) {
		// Logic from tryHarvestBlock for pre-canceling the event
		boolean preCancelEvent = false;
		ItemStack itemstack = entityPlayer.getMainHandStack();
		if (!itemstack.isEmpty() && !itemstack.getItem().canMine(world.getBlockState(pos), world, pos, entityPlayer)) {
			preCancelEvent = true;
		}

		if (gameType.isBlockBreakingRestricted()) {
			if (gameType == GameMode.SPECTATOR)
				preCancelEvent = true;

			if (!entityPlayer.canModifyBlocks()) {
				if (itemstack.isEmpty() || !itemstack.canDestroy(world.getRegistryManager().get(Registry.BLOCK_KEY), new CachedBlockPosition(world, pos, false)))
					preCancelEvent = true;
			}
		}

		// Tell client the block is gone immediately then process events
		if (world.getBlockEntity(pos) == null) {
			entityPlayer.networkHandler.sendPacket(new BlockUpdateS2CPacket(pos, world.getFluidState(pos).getBlockState()));
		}

		// Post the block break event
		BlockState state = world.getBlockState(pos);
		BlockEvents.BreakEvent event = new BlockEvents.BreakEvent(world, pos, state, entityPlayer);
		event.setCanceled(preCancelEvent);
		event.sendEvent();

		// Handle if the event is canceled
		if (event.isCanceled()) {
			// Let the client know the block still exists
			entityPlayer.networkHandler.sendPacket(new BlockUpdateS2CPacket(world, pos));

			// Update any tile entity data for this block
			BlockEntity blockEntity = world.getBlockEntity(pos);
			if (blockEntity != null) {
				Packet<?> pkt = blockEntity.getUpdatePacket();
				if (pkt != null) {
					entityPlayer.networkHandler.sendPacket(pkt);
				}
			}
		}
		return event.isCanceled() ? -1 : event.getExpToDrop();
	}

	/**
	 * Handles the modification of loot table drops via the registered Global Loot Modifiers,
	 * so that custom effects can be processed.
	 *
	 * <p>All loot-table generated loot should be passed to this function.</p>
	 *
	 * @param lootTableId The ID of the loot table currently being queried
	 * @param generatedLoot The loot generated by the loot table
	 * @param context The loot context that generated the loot, unmodified
	 * @return The modified list of drops
	 *
	 * @apiNote The given context will be modified by this method to also store the ID of the
	 *          loot table being queried.
	 */
	public static List<ItemStack> modifyLoot(Identifier lootTableId, List<ItemStack> generatedLoot, LootContext context) {
		context.setQueriedLootTableId(lootTableId); // In case the ID was set via copy constructor, this will be ignored: intended
		LootModifierManager man = LootModifierManager.getLootModifierManager();
		for (IGlobalLootModifier mod : man.getAllLootMods()) {
			generatedLoot = mod.apply(generatedLoot, context);
		}
		return generatedLoot;
	}

	public static void init() {
		ServerEntityEvents.ENTITY_LOAD.register((entity, world) -> {
			if (entity instanceof MultiPartEntity partEntity && partEntity.isMultipartEntity()) {
				PartEntity<?>[] parts = partEntity.getParts();
				if (parts != null) {
					for (PartEntity<?> part : parts) {
						world.getPartEntityMap().put(part.getId(), part);
					}
				}
			}
		});
		ServerEntityEvents.ENTITY_UNLOAD.register((entity, world) -> {
			if(entity instanceof MultiPartEntity partEntity && partEntity.isMultipartEntity()) {
				PartEntity<?>[] parts = partEntity.getParts();
				if (parts != null) {
					for (PartEntity<?> part : parts) {
						world.getPartEntityMap().remove(part.getId());
					}
				}
			}
		});
		EntityEvents.ON_JOIN_WORLD.register((entity, world, loadedFromDisk) -> {
			if (entity.getClass().equals(ItemEntity.class)) {
				ItemStack stack = ((ItemEntity)entity).getStack();
				Item item = stack.getItem();
				if (item.hasCustomEntity(stack)) {
					Entity newEntity = item.createEntity(world, entity, stack);
					if (newEntity != null) {
						entity.discard();
						var executor = LogicalSidedProvider.WORKQUEUE.get(world.isClient ? EnvType.CLIENT : EnvType.SERVER);
						executor.send(new ServerTask(0, () -> world.spawnEntity(newEntity)));
						return false;
					}
				}
			}
			return true;
		});
		RegistryEntryRemovedCallback.event(Registry.ITEM).register((rawId, id, item) -> {
			if (item instanceof BlockItemExtensions blockItem) {
				blockItem.removeFromBlockToItemMap(Item.BLOCK_ITEMS, item);
			}
		});
		ModsLoadedCallback.EVENT.register(envType -> {
			Registry.FLUID.forEach(fluid -> {
				if (envType == EnvType.SERVER && FluidVariantAttributes.getHandler(fluid) == null)
					FluidVariantAttributes.register(fluid, new FluidVariantFluidAttributesHandler(fluid.getAttributes()));
			});
		});
	}

	public static FluidAttributes getFluidAttributesFromVariant(Fluid fluid) {
		if (!fluid.isStill(fluid.getDefaultState()) && fluid instanceof FlowableFluid flowingFluid)
			return flowingFluid.getStill().getAttributes();
		if (!fluid.isStill(fluid.getDefaultState()) && fluid != Fluids.EMPTY)
			return Fluids.WATER.getAttributes(); // Return waters attributes if all else fails
		FluidVariantAttributeHandler handler = FluidVariantAttributes.getHandler(fluid);
		if (handler == null)
			handler = FluidVariantAttributes.getHandler(Fluids.WATER); // Default to water
		FluidVariant variant = FluidVariant.of(fluid);
		Identifier stillTexture = null;
		Identifier flowingTexture = null;
		Identifier overlayTexture = null;
		int color = -1;
		if (FabricLoader.getInstance().getEnvironmentType() == EnvType.CLIENT) {
			Sprite[] sprites = FluidVariantRendering.getSprites(variant);

			stillTexture = sprites[0] == null ? SimpleFluidRenderHandler.WATER_STILL : sprites[0].getId();
			flowingTexture = sprites[1] == null ? SimpleFluidRenderHandler.WATER_FLOWING : sprites[1].getId();
			if (sprites.length == 3)
				overlayTexture = sprites[2] == null ? SimpleFluidRenderHandler.WATER_OVERLAY : sprites[2].getId();
			color = FluidVariantRendering.getColor(variant);
		}
		FluidAttributes.Builder builder = FluidAttributes.builder(stillTexture, flowingTexture);
		builder.sound(handler.getFillSound(variant).orElse(null), handler.getEmptySound(variant).orElse(null));
		builder.overlay(overlayTexture);
		builder.viscosity(handler.getViscosity(variant, null));
		builder.luminosity(handler.getLuminance(variant));
		builder.temperature(handler.getTemperature(variant));
		if (handler.isLighterThanAir(variant))
			builder.gaseous();
		builder.color(color);
		return builder.build(fluid);
	}

	public static int getLootingLevel(Entity target, @Nullable Entity killer, @Nullable DamageSource cause) {
		if (killer instanceof LivingEntity)
			return EnchantmentHelper.getLooting((LivingEntity)killer);
		return 0;
	}
}
