package io.github.fabricators_of_create.porting_lib.loot;

import java.util.List;
import java.util.function.Predicate;
import net.minecraft.item.ItemStack;
import net.minecraft.loot.condition.LootCondition;
import net.minecraft.loot.condition.LootConditionTypes;
import net.minecraft.loot.context.LootContext;
import org.jetbrains.annotations.NotNull;


//From forge
public abstract class LootModifier implements IGlobalLootModifier {
	protected final LootCondition[] conditions;
	private final Predicate<LootContext> combinedConditions;

	/**
	 * Constructs a LootModifier.
	 *
	 * @param conditionsIn the ILootConditions that need to be matched before the loot is modified.
	 */
	protected LootModifier(LootCondition[] conditionsIn) {
		this.conditions = conditionsIn;
		this.combinedConditions = LootConditionTypes.joinAnd(conditionsIn);
	}

	@NotNull
	@Override
	public final List<ItemStack> apply(List<ItemStack> generatedLoot, LootContext context) {
		return this.combinedConditions.test(context) ? this.doApply(generatedLoot, context) : generatedLoot;
	}

	/**
	 * Applies the modifier to the generated loot (all loot conditions have already been checked
	 * and have returned true).
	 *
	 * @param generatedLoot the list of ItemStacks that will be dropped, generated by loot tables
	 * @param context       the LootContext, identical to what is passed to loot tables
	 * @return modified loot drops
	 */
	@NotNull
	protected abstract List<ItemStack> doApply(List<ItemStack> generatedLoot, LootContext context);
}
